import { RequiredDataFromCollectionSlug } from 'payload'
import type { PostArgs } from './post-1'

export const post5: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'responsive-design-2024',
    _status: 'published',
    title: 'Beyond Mobile-First: Responsive Design for Multi-Device Experiences',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Modern responsive design has evolved beyond simple breakpoints. Learn how we create fluid experiences across all devices using advanced techniques and thoughtful UX principles.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The landscape of devices accessing the web continues to diversify, from ultra-wide monitors to foldable phones and wearable tech. This evolution demands a more sophisticated approach to responsive design that goes beyond the traditional mobile-first paradigm.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "At Lilies Tech Zone, we've refined our approach to create truly flexible, device-agnostic experiences. Here are the key principles and techniques we apply to our client projects:",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '1. Fluid Typography Systems',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Static font sizes at specific breakpoints create jarring transitions as users resize browsers. Instead, we implement truly fluid typography that scales smoothly across viewport sizes:',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Fluid Typography with CSS Clamp',
              blockType: 'code',
              code: "/* Tailwind CSS config example */\ntheme: {\n  fontSize: {\n    xs: ['clamp(0.75rem, 0.7rem + 0.25vw, 0.875rem)', { lineHeight: '1.5' }],\n    sm: ['clamp(0.875rem, 0.8rem + 0.38vw, 1rem)', { lineHeight: '1.5' }],\n    base: ['clamp(1rem, 0.9rem + 0.5vw, 1.125rem)', { lineHeight: '1.75' }],\n    lg: ['clamp(1.125rem, 1rem + 0.63vw, 1.25rem)', { lineHeight: '1.75' }],\n    xl: ['clamp(1.25rem, 1.13rem + 0.75vw, 1.5rem)', { lineHeight: '1.75' }],\n    '2xl': ['clamp(1.5rem, 1.28rem + 1.13vw, 1.875rem)', { lineHeight: '1.4' }],\n    '3xl': ['clamp(1.875rem, 1.5rem + 1.88vw, 2.5rem)', { lineHeight: '1.4' }],\n    '4xl': ['clamp(2.5rem, 1.94rem + 2.8vw, 3.5rem)', { lineHeight: '1.25' }],\n    '5xl': ['clamp(3rem, 2.24rem + 3.8vw, 4.5rem)', { lineHeight: '1.1' }],\n  },\n}",
              language: 'typescript',
            },
            format: '',
            version: 2,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: 'Benefits:',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' Smooth scaling between device sizes, improved readability at all viewport widths, and reduced development time managing breakpoint-specific typography.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '2. Container Queries & The Layout Algorithm',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "While viewport-based media queries remain important, container queries enable components to respond to their parent container's size rather than the overall viewport:",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Container Query Example',
              blockType: 'code',
              code: '// Component that adapts based on its container width\nconst ResponsiveCard = () => {\n  return (\n    <div className="container-query-card">\n      <style jsx>{`\n        .container-query-card {\n          container-type: inline-size;\n          container-name: card;\n        }\n        \n        .card-content {\n          display: flex;\n          flex-direction: column;\n        }\n        \n        @container card (min-width: 400px) {\n          .card-content {\n            flex-direction: row;\n            align-items: center;\n          }\n          \n          .card-image {\n            width: 150px;\n            margin-right: 1rem;\n          }\n        }\n      `}</style>\n      \n      <div className="card-content">\n        <img className="card-image" src="/product.jpg" alt="Product" />\n        <div className="card-body">\n          <h3>Product Title</h3>\n          <p>Product description that adapts based on container width</p>\n        </div>\n      </div>\n    </div>\n  );\n};',
              language: 'typescript',
            },
            format: '',
            version: 2,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: 'Our layout algorithm:',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "We've developed a systematic approach that combines container queries, CSS Grid, and flexbox to create components that intelligently adapt based on their context within the layout.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '3. Responsive UX Patterns',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'True responsiveness goes beyond visual adaptation to consider interaction models appropriate for different devices:',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Touch-friendly targets',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Minimum 44×44px touch targets for mobile with appropriate spacing',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Context-aware navigation',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Different navigation patterns based on device capabilities',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Input adaptation',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Forms and inputs optimized for the expected input method (touch, keyboard, voice)',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Client Success Story',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'E-commerce conversion improvement:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' By implementing our responsive UX patterns, we helped an e-commerce client increase mobile conversion rates by 34% and reduce cart abandonment by 27%, while maintaining a consistent brand experience across all devices.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '4. Performance as a Responsive Design Feature',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Truly responsive design considers network conditions and device capabilities as part of the user experience:',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Conditional loading',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Using the Network Information API to adapt content based on connection quality',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Responsive images and video',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Modern image formats (WebP, AVIF) with appropriate srcset and sizes attributes',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Feature detection',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Progressive enhancement based on browser capability testing',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Responsive Images Example',
              blockType: 'code',
              code: '// Next.js Image component with responsive sizing\nimport Image from \'next/image\';\n\nconst ResponsiveProductImage = ({ product }) => {\n  return (\n    <div className="relative w-full h-0 pb-[100%] sm:pb-[75%] md:pb-[66.67%]">\n      <Image\n        src={product.image}\n        alt={product.name}\n        fill\n        sizes="(max-width: 640px) 100vw, \n               (max-width: 1024px) 50vw, \n               33vw"\n        className="object-cover"\n        priority={product.featured}\n        quality={80}\n      />\n    </div>\n  );\n};',
              language: 'typescript',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '5. Testing Across the Device Spectrum',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our comprehensive testing approach ensures consistent experiences across the device spectrum:',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Continuous testing',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Automated visual regression tests across breakpoints',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• Real device lab',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Physical testing on popular devices and screen sizes',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: '• User testing sessions',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ': Observing real users interact with designs across different devices',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Conclusion: Device-Agnostic Design',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The most effective responsive design approach for 2024 and beyond is one that transcends specific device categories to create truly fluid experiences. By combining fluid typography, container queries, responsive UX patterns, performance optimization, and comprehensive testing, we create web applications that provide optimal experiences regardless of how users access them.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'This device-agnostic approach not only improves current user experiences but also future-proofs applications against the continuing evolution of the device landscape.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Ready to improve your responsive strategy?',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: 'Let us help you implement these advanced responsive design techniques in your web application. ',
                          version: 1,
                        },
                        {
                          type: 'link',
                          children: [
                            {
                              type: 'text',
                              detail: 0,
                              format: 0,
                              mode: 'normal',
                              style: '',
                              text: 'Contact our team',
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                          fields: {
                            linkType: 'custom',
                            newTab: false,
                            url: '/contact',
                          },
                          format: '',
                          indent: 0,
                          version: 3,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' to discuss your project needs.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'info',
            },
            format: '',
            version: 2,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Learn how modern responsive design has evolved beyond mobile-first to create fluid, device-agnostic experiences with container queries, fluid typography, and contextual UX patterns.',
      image: heroImage.id,
      title: 'Beyond Mobile-First: Responsive Design for Multi-Device Experiences',
    },
    relatedPosts: [], // this is populated by the seed script
  }
}
